name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      run: |
        export VERSION=$(aws s3 ls s3://dev-xpro/dev-xpro.c3spectra.cloud/ --recursive | awk '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//' | grep 'v[1-9]' | cut -d"/" -f2 | sort | uniq | cut -d"v" -f2 | tail -1)
        export NEW_VERSION=${VERSION}+1
        echo "Old Version: $VERSION and New Version: $NEW_VERSION"
        #aws s3 sync ./dist/angular-github-actions-amazon-s3 s3://dev-xpro/dev-xpro.c3spectra.cloud/${VERSION}


